### ISSUE TITLE
Batch size bigger than 1

### ISSUE THREAD

**Issue by l1997i** [ouenal/scribblekitti#3]
Thanks so much for your excellent work and code. I've a question about the dataloader code. Is it possible to set the batch size bigger than 1 (e.g., 4, 8 or 16). When I tried to set a bigger `batch_size` in `training.yaml`, the code went wrong with the error "RuntimeError: stack expects each tensor to be equal size, but got [124266, 3] at entry 0 and [112695, 3] at entry 1".

```yml
# in `training.yaml`
train_dataloader:
  batch_size: 4       # default is 1
  shuffle: True
  num_workers: 4
```

Thanks in advance!
